### ISSUE TITLE
Error : let glob = undefined

### ISSUE THREAD

**Issue by Bruno92400** [isaacs/rimraf#196] opened 2019-08-14 16:14 UTC
Hi,

In my API, rimraf is used and works since a few years with gulp.
I change nothing in my gulpfile but since about one week there is this error and i found nothing to fix it : 
![image](https://user-images.githubusercontent.com/12731997/63037152-c7ffbb00-bebe-11e9-9d61-57c1503e56de.png)

Anyone can help me for this?

Best regards,
Bruno

**Comment by basavk** [comment] 2019-08-14 16:44
This is the duplicate of #195 . 
Faced the same issue on our production systems on today morning.
@Bruno92400 One of your transitive dependencies must be pulling the latest version(v2.7.0) of rimraf which is causing the breakage.

To resolve the issue either upgrade your node version to 6.4.0 or downgrade rimraf to 2.6.3 in your package.json file

**Comment by isaacs** [comment] 2019-08-14 16:55
https://github.com/isaacs/rimraf/commit/012ecbba814a74c3201ef63c54f6abcefa671be4

**Closed by isaacs** 2019-08-14 16:55 UTC

**Comment by basavk** [comment] 2019-08-14 16:56
Thanks @isaacs for quick v2.7.1 release.

**Comment by Bruno92400** [comment] 2019-08-14 20:58
It works, thank you very much!!!
